### ISSUE TITLE
Node 6.1 unsupported target

### ISSUE THREAD

**Issue by huseyinkozan** [tessel/t2-compiler#25]
Hello,

I have tried to compile serialport for NodeJS 6.1 to run in firmware that I grab here :
https://github.com/tessel/openwrt-tessel/pull/58

Here the compile output:
https://gist.github.com/huseyinkozan/8e0e984b9eda65f48f50a92f4412e103

**Comment by huseyinkozan** [comment]
t2-compile is at this commit:
huseyinkozan/t2-compiler@59c9580

**Comment by rwaldron** [comment]
There is currently no way for t2-cli to know what version of node is running on a tessel, which would be necessary to determine which pre-compiled binary to use.

**Comment by rwaldron** [comment]
Actually, I'm mistaken—I forgot that this had been added recently.

**Comment by rwaldron** [comment]
All existing precompiled module tarballs have no version information... this is going to be a huge mess.

**Comment by huseyinkozan** [comment]
I started to try to build for a deployment error that states serialport binary did not exists. Here is the error I got :

```
$ t2 push index.js
INFO Looking for your Tessel...
INFO Connected to Tessel.
INFO Building project.
ERR! Error: ENOENT: no such file or directory, stat '/home/huseyinkozan/.tessel/binaries/serialport-3.1.2-Release/obj.target/serialport.node'
```

**Comment by rwaldron** [comment]
I've just been able to precompile all of our existing modules to 6.5.0. There is presently no way to easily change the version—I just updated 4.5.0 -> 6.5.0 throughout and rebuilt my vagrant box. Since this is being handled through a set of interconnected issues, I'm going to close this.
