### ISSUE TITLE
Make Node 6 precompiled binaries for all existing Node 4 precompiled binaries

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-compiler#34]
Blocked by https://github.com/tessel/t2-compiler/issues/32
Blocked by https://github.com/tessel/t2-compiler/issues/33
Blocks https://github.com/tessel/t2-firmware/issues/206

**Comment by rwaldron** [comment]
![](https://i.gyazo.com/cf96371063bab91da45dc5ec51aa61b4.png)

**Comment by johnnyman727** [comment]
:clap:

**Comment by tikurahul** [comment]
:+1:
