### ISSUE TITLE
Node 6.5.0: Compilation failure list

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-compiler#36]
This list contains the binary modules that failed to compile for 6.5.0 during our migration. It's unlikely that t2-compiler is the cause, so this list is purely for us to use as a reference. In most cases, the module needs to be updated to use a newer version of Nan
- ~~gamepad@1.2.2~~
- ~~grpc@1.0.0~~
- ~~sqlite3@3.1.4 (cc @nolanlawson)~~

**Comment by nolanlawson** [comment]
Yeah from the little bit I explored with sqlite3 it seems like there are just some really tricky things going on in the gyp bindings. Might be good to open an issue on their repo.

**Comment by rwaldron** [comment]
@nolanlawson thanks for checking in on that—did you file an issue we can link to?

**Comment by tcr** [comment]
@rwaldron 1.3.0 of gamepad was published and works with node ABI 48 (Node 6)

**Comment by tcr** [comment]
GRPC is blocked by my PR: https://github.com/grpc/grpc/pull/8208

**Comment by tcr** [comment]
Note, GRPC release builds work fine so I suggest we publish those. Only debug builds are affected.

**Comment by tcr** [comment]
sqlite now works with release of https://github.com/tessel/pre-gypify 1.7.0.

**Comment by rwaldron** [comment]
Very cool :D
