### ISSUE TITLE
Unable to upload code to vm

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-compiler#4]
Even after working around #2, I was not able to compile and upload to my VM. I received this error:

```
➜  hello-world git:(master) ✗ t2-compiler populate --target=vm
target=vm
Waiting for VM "tessel2-compiler" to power on...
VM "tessel2-compiler" has been successfully started.
Uploading package...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:766:14)
```

It seems to be originating from somewhere around [here](https://github.com/tessel/t2-compiler/blob/master/build.js#L125-L131) based on the pipe isssue.

**Comment by rwaldron** [comment]
@HipsterBrown and I encountered a (likely) similar issue. (Unhandled rejection of some sort)

**Comment by johnnyman727** [comment]
This was fixed with https://github.com/tessel/t2-compiler/commit/ac95ab8781b41c7dca97e6c8f5f2d1cb7b175f90.
